import 'package:autogram/deep_links.dart';
import 'package:autogram/push_messages.dart';
import 'package:test/test.dart';

/// Tests for the [parseSignRequestMessage] function.
void main() {
  const guid = "e7e95411-66a1-d401-e063-0a64dbb6b796";
  const key = "EeESAfZQh9OTf5qZhHZtgaDJpYtxZD6TIOQJzRgRFgQ=";

  group('parseSignRequestMessage', () {
    test('parseSignRequestMessage parses plain JSON message', () {
      const message =
          '{"document_guid":"$guid","documentEncryptionKey":"$key"}';
      final value = parseSignRequestMessage(message, null);

      expect(value.documentGuid, guid);
      expect(value.documentEncryptionKey, key);
    });

    test('parseSignRequestMessage parses camelCase JSON message', () {
      const message = '{"documentGuid":"$guid","documentEncryptionKey":"$key"}';
      final value = parseSignRequestMessage(message, null);

      expect(value.documentGuid, guid);
      expect(value.documentEncryptionKey, key);
    });

    test('parseSignRequestMessage decrypts Rails MessageEncryptor message', () {
      // Generated by ActiveSupport::MessageEncryptor (aes-256-gcm, JSON)
      const pushkey = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=";
      const message =
          "HUcDNMczpsM2aT9c+WiWMGgH0RJEz8uz8HEqSM62gejoH3FnCoQKiIa9uJeCwHr2ct0rEK3AL5hquw20qJdN5AAt7Bf2ql05M5K8RNzEQZFGuGSd7d0SWpnUJAF3phF/HpkYE5VrbD+DHTloCl69Xuexp7TJlVuNFo7kSOBGWOYUl6r4QFZSkG4=--TGkfHM+5jFVtCFz/--+9Cpsy/DETccC2Cda11p1Q==";
      final value = parseSignRequestMessage(message, pushkey);

      expect(value.documentGuid, guid);
      expect(value.documentEncryptionKey, key);
    });

    test('parseSignRequestMessage throws for invalid message', () {
      expect(
        () => parseSignRequestMessage('{"document_guid":"$guid"}', null),
        throwsFormatException,
      );
      expect(
        () => parseSignRequestMessage("abc--def--ghi", null),
        throwsFormatException,
      );
      expect(
        () => parseSignRequestMessage("abc", "AAAA"),
        throwsFormatException,
      );
    });

    test('SignRequestMessage.toUri returns parsable deep link', () {
      const message = SignRequestMessage(
        documentGuid: guid,
        documentEncryptionKey: key,
      );
      final action = parseDeepLinkAction(message.toUri());

      expect(action, const TypeMatcher<SignRemoteDocumentAction>());
      expect((action as SignRemoteDocumentAction).guid, guid);
      expect(action.key, key);
      expect(action.integration, isNull);
    });
  });
}
