name: autogram
description: "Autogram v mobile"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  eidmsdk:
    path: ../eidmsdk_flutter
  autogram_sign:
    path: ../autogram_sign
  chopper: any
  injectable: ^2.2.0
  get_it: ^7.6.1
  flutter_hooks: ^0.20.5
  localstorage: ^4.0.1+4
  share_plus: ^7.2.2
  printing: ^5.12.0
  logging:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: any
  injectable_generator: ^2.2.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
