name: autogram
description: "Autogram v mobile"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+22

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  eidmsdk:
    path: ../eidmsdk_flutter
  autogram_sign:
    path: ../autogram_sign
  flutter_svg:
  package_info_plus: ^5.0.1
  chopper:
  injectable: ^2.2.0
  get_it: ^7.6.1
  flutter_hooks: ^0.20.5
  localstorage: ^4.0.1+4
  share_plus: ^7.2.2
  pdf:
  printing: ^5.12.0
  webview_flutter:
  webview_flutter_web:
  logging:
  path:
  path_provider:
  file_picker:
  flutter_bloc: ^8.0.0
  provider:
  basic_utils:
  intl:
  dotted_border: ^2.1.0
  notified_preferences:
  widgetbook_annotation: ^3.1.0
  widgetbook: ^3.7.0
  firebase_core:
  firebase_crashlytics:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test:
  build_runner:
  injectable_generator: ^2.2.0
  widgetbook_generator: ^3.7.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    # TODO Use svg.vec https://pub.dev/packages/flutter_svg#precompiling-and-optimizing-svgs
    - assets/icons/menu.svg
    - assets/icons/qr_code_scanner.svg
    - assets/images/autogram_logo.png
    - assets/images/close.png
    - assets/images/lock.png
    - assets/images/notification.png
    - assets/images/result_error.png
    - assets/images/result_info.png
    - assets/images/result_success.png
  fonts:
    - family: Source Sans 3
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
        - asset: assets/fonts/SourceSans3-It.ttf
          style: italic
        - asset: assets/fonts/SourceSans3-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSans3-BoldIt.ttf
          weight: 700
          style: italic
