name: autogram
description: "Autogram v mobile"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.1+38

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  eidmsdk:
    git:
      url: https://github.com/slovensko-digital/eidmsdk-flutter
      ref: 027083b4ea0b453eab08b575bfc0ca71a121c035
  autogram_sign:
    git:
      url: https://github.com/slovensko-digital/avm-client-dart
      ref: v0.4.4
  package_info_plus:
  share_plus:
  wakelock_plus:
  flutter_svg:
  http:
  chopper: '>=7.4.0 <8.0.0'
  injectable:
  get_it:
  flutter_hooks:
  localstorage: '>=4.0.0 <5.0.0'
  pdf:
  printing:
  webview_flutter:
  webview_flutter_web:
  logging:
  path:
  path_provider:
  file_picker:
  flutter_bloc:
  provider:
  basic_utils:
  intl:
  dotted_border:
  notified_preferences:
  widgetbook_annotation:
  widgetbook:
  firebase_core: 2.27.0
  firebase_crashlytics: 3.4.18
  url_launcher:
  mobile_scanner: 4.0.1 # TODO Update mobile_scanner  to v6.x
  html:
  flutter_markdown:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test:
  build_runner:
  injectable_generator: ^2.2.0
  widgetbook_generator: ^3.7.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/menu.svg
    - assets/icons/qr_code_scanner.svg
    - assets/images/autogram_logo.png
    - assets/images/close.svg
    - assets/images/lock.svg
    - assets/images/notification.svg
    - assets/images/danger.svg
    - assets/images/info.svg
    - assets/images/tick.svg
  fonts:
    - family: Source Sans 3
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
        - asset: assets/fonts/SourceSans3-It.ttf
          style: italic
        - asset: assets/fonts/SourceSans3-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSans3-BoldIt.ttf
          weight: 700
          style: italic
