name: Build application for iOS

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release-Build-iOS"
        default: "Generate release build for iOS"

permissions:
  contents: write

jobs:
  build:
    environment: packaging
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: app

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Test
        working-directory: ./app
        run: flutter test

      - name: Build iOS .ipa
        working-directory: ./app
        # https://docs.flutter.dev/deployment/ios#create-an-app-bundle
        run: flutter build ipa --release
